# Runs validate_reactions.py on all new and changed files in this PR.

name: Submission

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ord-submissions-test
      uses: actions/checkout@v2
      with:
        path: ord-submissions
    - name: Fetch master and identify changed files
      run: |
        cd "${GITHUB_WORKSPACE}/ord-submissions"
        git remote add upstream https://github.com/Open-Reaction-Database/ord-submissions-test.git
        echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
        git fetch --no-tags --prune --depth=1 upstream +refs/heads/*:refs/remotes/upstream/*
        git diff --name-only upstream/master > changed_files.txt
        # Use `|| [[ $? == 1 ]]` in case no lines match and the exit code is nonzero.
        grep -e "\.pbtxt$" changed_files.txt > changed_pbtxt_files.txt || [[ $? == 1 ]]
        LOCAL_NUM_CHANGED="$(wc -l < changed_pbtxt_files.txt | tr -d ' ')"
        echo "::set-env name=NUM_CHANGED_FILES::${LOCAL_NUM_CHANGED}"
        echo "Found ${LOCAL_NUM_CHANGED} changed pbtxt files"
    - name: Checkout ord-schema
      uses: actions/checkout@v2
      with:
        # TODO(kearnes): Use upstream master.
        repository: skearnes/ord-schema
        ref: process
        path: ord-schema
      if: env.NUM_CHANGED_FILES != '0'
    - name: Install miniconda
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
        python-version: '3.7'
        auto-update-conda: true
      if: env.NUM_CHANGED_FILES != '0'
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        cd "${GITHUB_WORKSPACE}/ord-schema"
        conda install --file requirements.txt
        conda install -c rdkit rdkit
      if: env.NUM_CHANGED_FILES != '0'
    - name: Install ord_schema
      shell: bash -l {0}
      run: |
        cd "${GITHUB_WORKSPACE}/ord-schema"
        pip install -r requirements.txt
        python setup.py install
      if: env.NUM_CHANGED_FILES != '0'
    - name: Validate submission
      shell: bash -l {0}
      run: |
        cd "${GITHUB_WORKSPACE}/ord-submissions"
        python "${GITHUB_WORKSPACE}/ord-schema/ord_schema/process_dataset.py" \
          --input_file=changed_pbtxt_files.txt \
          --input_format=pbtxt \
          --update \
          --cleanup
      if: env.NUM_CHANGED_FILES != '0'
    - name: Commit updates
      run: |
        cd "${GITHUB_WORKSPACE}/ord-submissions"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Automatic update by process_datasets.py"
        git push
      if: env.NUM_CHANGED_FILES != '0'
